// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const FALLBACK_SUPABASE_URL = 'https://c--9eb8642f-c04f-4194-8142-ddbbf1b88786-prod.lovable.cloud';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_H_RhQ_PIDP9b82ZNqqa69w_2juXGuTH';

function normalizeSupabaseUrl(value?: string): string {
  if (!value) return FALLBACK_SUPABASE_URL;

  const trimmed = value.trim();
  if (!trimmed) return FALLBACK_SUPABASE_URL;

  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
      return parsed.origin.replace(/\/$/, '');
    }
  } catch {
    // ignore malformed values and keep the Lovable fallback URL
  }

  return FALLBACK_SUPABASE_URL;
}

function getSupabaseClientConfig() {
  const rawUrl = typeof import.meta !== 'undefined' ? import.meta.env?.['VITE_SUPABASE_URL'] ?? process.env?.['SUPABASE_URL'] : process.env?.['SUPABASE_URL'];
  const rawKey = typeof import.meta !== 'undefined' ? import.meta.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'] ?? process.env?.['SUPABASE_PUBLISHABLE_KEY'] : process.env?.['SUPABASE_PUBLISHABLE_KEY'];

  return {
    url: normalizeSupabaseUrl(rawUrl),
    key: (rawKey || FALLBACK_SUPABASE_PUBLISHABLE_KEY).trim(),
  };
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = getSupabaseClientConfig();

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

