// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://c--9eb8642f-c04f-4194-8142-ddbbf1b88786-prod.lovable.cloud';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_H_RhQ_PIDP9b82ZNqqa69w_2juXGuTH';

function sanitizeSupabaseKey(value?: string): string {
  const normalized = (value ?? '').trim();
  if (!normalized || !normalized.startsWith('sb_')) {
    return FALLBACK_SUPABASE_PUBLISHABLE_KEY;
  }
  return normalized;
}

function normalizeSupabaseUrl(value?: string): string {
  if (!value) return FALLBACK_SUPABASE_URL;

  const trimmed = value.trim();
  if (!trimmed) return FALLBACK_SUPABASE_URL;

  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
      return parsed.origin.replace(/\/$/, '');
    }
  } catch {
    // ignore malformed values and keep the Lovable fallback URL
  }

  return FALLBACK_SUPABASE_URL;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  const safeSupabaseKey = sanitizeSupabaseKey(supabaseKey);

  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(safeSupabaseKey) && headers.get('Authorization') === `Bearer ${safeSupabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', safeSupabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const rawUrl = process.env['SUPABASE_URL'];
  const rawKey = process.env['SUPABASE_SERVICE_ROLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  const SUPABASE_URL = rawUrl ? normalizeSupabaseUrl(rawUrl) : null;
  const SUPABASE_SERVICE_ROLE_KEY = sanitizeSupabaseKey(rawKey || FALLBACK_SUPABASE_PUBLISHABLE_KEY);

  if (!SUPABASE_URL) {
    console.warn('[Supabase] Missing server env SUPABASE_URL; using safe fallback for SSR.');
    return null as unknown as ReturnType<typeof createSupabaseAdminClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    if (!_supabaseAdmin) {
      return undefined;
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
